[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[project]
name = "yggdrasil-relation-discovery"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "yggdrasil-sdk"
]

[project.entry-points."yggdrasil.modules"]
relation-discovery = "yggdrasil_relation_discovery.plugin:plugin"

[tool.hatch.build.targets.wheel]
packages = ["src/yggdrasil_relation_discovery"]