from __future__ import annotations

from datetime import datetime
from typing import Any

import sqlalchemy as sa
from sqlalchemy.orm import Session

from ...contracts import (
    ActorRef,
    BudgetState,
    EntityRef,
    ModuleConfigBinding,
    EventSubscriptionRecord,
    EventEnvelope,
    EventHandlingResult,
    ExternalRef,
    HealthReport,
    HookContributionRecord,
    ModelRouteDecision,
    ModuleCatalogSnapshot,
    ModuleInstallRecord,
    ModuleManifestSummary,
    PullRequestRecord,
    ReviewCommentRecord,
    TaskSnapshotSummary,
)
from ...domain import (
    AgentRunRecord,
    AssetEmbeddingRecord,
    AssetRecord,
    AssetSegmentRecord,
    DatasetVersionRecord,
    EdgeRecord,
    EvaluationRunRecord,
    EvaluationSuiteRecord,
    ImportFragmentRecord,
    ImportJobRecord,
    ImportPolicy,
    MailboxMessageRecord,
    MemoryBranchRecord,
    ModelArtifactRecord,
    ModelInvocationRecord,
    NodeRecord,
    NodeVersionRecord,
    OutboxRecord,
    PermissionTupleRecord,
    ProjectRecord,
    PromptCompileArtifactRecord,
    PromptProfileVersionRecord,
    RetrievalBundle,
    RetrievalRequestRecord,
    SeedTemplateVersionRecord,
    SideChannelEventRecord,
    SourceAnnotationRecord,
    SpaceRecord,
    SpaceMountRecord,
    TaskRecord,
    TreePlanRecord,
)
from ...support import new_id, utc_now
from ..constants import (
    DEFAULT_APP_ID,
    DEFAULT_BRANCH_ID,
    DEFAULT_OWNER_PROFILE_ID,
    DEFAULT_PROJECT_ID,
    DEFAULT_SPACE_ID,
    ROOT_BRANCH_CONTENTS,
    ROOT_BRANCH_TITLES,
)
from ..orm import (
    AgentRunORM,
    AssetEmbeddingORM,
    AssetORM,
    AssetSegmentORM,
    DatasetVersionORM,
    EdgeORM,
    EvaluationRunORM,
    EvaluationSuiteORM,
    EventSubscriptionORM,
    HealthReportORM,
    HookContributionORM,
    ImportFragmentORM,
    ImportJobORM,
    MailboxMessageORM,
    MemoryBranchORM,
    ModelArtifactORM,
    ModelInvocationORM,
    ModelRouteDecisionORM,
    ModuleConfigBindingORM,
    ModuleInstallORM,
    NodeORM,
    NodeVersionORM,
    OutboxRecordORM,
    PermissionTupleORM,
    ProjectORM,
    PromptCompileArtifactORM,
    PromptProfileVersionORM,
    RetrievalRequestORM,
    PullRequestORM,
    ReviewCommentORM,
    SeedTemplateVersionORM,
    SideChannelEventORM,
    SourceAnnotationORM,
    SpaceORM,
    SpaceMountORM,
    TaskORM,
    TaskSnapshotORM,
    TreePlanORM,
)



