"""persistence_base

Revision ID: 553bffc21802
Revises: 
Create Date: 2026-04-16 21:56:27.098797

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


Text = sa.Text


# revision identifiers, used by Alembic.
revision = '553bffc21802'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
        op.execute("CREATE EXTENSION IF NOT EXISTS ltree")
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('module_installs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('module_id', sa.String(length=128), nullable=False),
    sa.Column('module_version', sa.String(length=64), nullable=False),
    sa.Column('desired_state', sa.String(length=32), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('runtime_mode', sa.String(length=32), nullable=False),
    sa.Column('manifest_ref', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('config_binding_id', sa.String(length=128), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module_installs')),
    sa.UniqueConstraint('module_id', name=op.f('uq_module_installs_module_id'))
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('export_policy', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('event_subscriptions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('module_install_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('consumer_group', sa.String(length=255), nullable=False),
    sa.Column('delivery_mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['module_install_id'], ['module_installs.id'], name=op.f('fk_event_subscriptions_module_install_id_module_installs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_subscriptions'))
    )
    op.create_index(op.f('ix_event_subscriptions_module_install_id'), 'event_subscriptions', ['module_install_id'], unique=False)
    op.create_table('health_reports',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('module_install_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details_ref', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['module_install_id'], ['module_installs.id'], name=op.f('fk_health_reports_module_install_id_module_installs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_reports')),
    sa.UniqueConstraint('module_install_id', name=op.f('uq_health_reports_module_install_id'))
    )
    op.create_table('hook_contributions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('module_install_id', sa.String(length=128), nullable=False),
    sa.Column('hook_name', sa.String(length=128), nullable=False),
    sa.Column('implementation_ref', sa.String(length=255), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('side_effects', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['module_install_id'], ['module_installs.id'], name=op.f('fk_hook_contributions_module_install_id_module_installs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hook_contributions'))
    )
    op.create_index(op.f('ix_hook_contributions_module_install_id'), 'hook_contributions', ['module_install_id'], unique=False)
    op.create_table('module_config_bindings',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('module_install_id', sa.String(length=128), nullable=False),
    sa.Column('config_schema_version', sa.String(length=64), nullable=False),
    sa.Column('effective_config_ref', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source_mode', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['module_install_id'], ['module_installs.id'], name=op.f('fk_module_config_bindings_module_install_id_module_installs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module_config_bindings')),
    sa.UniqueConstraint('module_install_id', name=op.f('uq_module_config_bindings_module_install_id'))
    )
    op.create_table('outbox_records',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=True),
    sa.Column('aggregate_type', sa.String(length=128), nullable=False),
    sa.Column('aggregate_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('payload_ref', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('publish_status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_outbox_records_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_records'))
    )
    op.create_index(op.f('ix_outbox_records_aggregate_id'), 'outbox_records', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_records_aggregate_type'), 'outbox_records', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_outbox_records_event_type'), 'outbox_records', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_records_project_id'), 'outbox_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_outbox_records_publish_status'), 'outbox_records', ['publish_status'], unique=False)
    op.create_table('spaces',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('space_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_subject', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_spaces_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spaces'))
    )
    op.create_index(op.f('ix_spaces_project_id'), 'spaces', ['project_id'], unique=False)
    op.create_table('memory_branches',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('space_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_branch_id', sa.String(length=128), nullable=True),
    sa.Column('head_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['base_branch_id'], ['memory_branches.id'], name=op.f('fk_memory_branches_base_branch_id_memory_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_memory_branches_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_memory_branches_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_branches'))
    )
    op.create_index(op.f('ix_memory_branches_project_id'), 'memory_branches', ['project_id'], unique=False)
    op.create_index(op.f('ix_memory_branches_space_id'), 'memory_branches', ['space_id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('space_id', sa.String(length=128), nullable=False),
    sa.Column('branch_id', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.String(length=128), nullable=True),
    sa.Column('root_branch', sa.String(length=32), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('detail_level', sa.Integer(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('forget_rate', sa.Float(), nullable=False),
    sa.Column('feedforward_score', sa.Float(), nullable=False),
    sa.Column('access_score', sa.Float(), nullable=False),
    sa.Column('activity_k', sa.Float(), nullable=False),
    sa.Column('float_score', sa.Float(), nullable=False),
    sa.Column('latest_version_id', sa.String(length=128), nullable=False),
    sa.Column('merged_into_node_id', sa.String(length=128), nullable=True),
    sa.Column('children_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('tree_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['memory_branches.id'], name=op.f('fk_nodes_branch_id_memory_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merged_into_node_id'], ['nodes.id'], name=op.f('fk_nodes_merged_into_node_id_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['nodes.id'], name=op.f('fk_nodes_parent_id_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_nodes_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_nodes_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nodes'))
    )
    op.create_index(op.f('ix_nodes_branch_id'), 'nodes', ['branch_id'], unique=False)
    op.create_index(op.f('ix_nodes_parent_id'), 'nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_nodes_project_id'), 'nodes', ['project_id'], unique=False)
    op.create_index(op.f('ix_nodes_space_id'), 'nodes', ['space_id'], unique=False)
    op.create_table('pull_requests',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('source_branch_id', sa.String(length=128), nullable=False),
    sa.Column('target_branch_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('reviewed_by', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_pull_requests_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_branch_id'], ['memory_branches.id'], name=op.f('fk_pull_requests_source_branch_id_memory_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_branch_id'], ['memory_branches.id'], name=op.f('fk_pull_requests_target_branch_id_memory_branches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pull_requests'))
    )
    op.create_index(op.f('ix_pull_requests_project_id'), 'pull_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_source_branch_id'), 'pull_requests', ['source_branch_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_target_branch_id'), 'pull_requests', ['target_branch_id'], unique=False)
    op.create_table('source_annotations',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('branch_id', sa.String(length=128), nullable=False),
    sa.Column('owner_kind', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('inference_summary', sa.Text(), nullable=True),
    sa.Column('evidence_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['memory_branches.id'], name=op.f('fk_source_annotations_branch_id_memory_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_source_annotations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_annotations'))
    )
    op.create_index(op.f('ix_source_annotations_branch_id'), 'source_annotations', ['branch_id'], unique=False)
    op.create_index(op.f('ix_source_annotations_owner_id'), 'source_annotations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_source_annotations_project_id'), 'source_annotations', ['project_id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('space_id', sa.String(length=128), nullable=False),
    sa.Column('branch_id', sa.String(length=128), nullable=False),
    sa.Column('from_node_id', sa.String(length=128), nullable=False),
    sa.Column('to_node_id', sa.String(length=128), nullable=False),
    sa.Column('relation_type', sa.String(length=128), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('evidence_annotation_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['memory_branches.id'], name=op.f('fk_edges_branch_id_memory_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_node_id'], ['nodes.id'], name=op.f('fk_edges_from_node_id_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_edges_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_edges_space_id_spaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['nodes.id'], name=op.f('fk_edges_to_node_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edges'))
    )
    op.create_index(op.f('ix_edges_branch_id'), 'edges', ['branch_id'], unique=False)
    op.create_index(op.f('ix_edges_from_node_id'), 'edges', ['from_node_id'], unique=False)
    op.create_index(op.f('ix_edges_project_id'), 'edges', ['project_id'], unique=False)
    op.create_index(op.f('ix_edges_space_id'), 'edges', ['space_id'], unique=False)
    op.create_index(op.f('ix_edges_to_node_id'), 'edges', ['to_node_id'], unique=False)
    op.create_table('node_versions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('title_snapshot', sa.String(length=255), nullable=False),
    sa.Column('content_snapshot', sa.Text(), nullable=False),
    sa.Column('parent_id_snapshot', sa.String(length=128), nullable=True),
    sa.Column('score_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('change_reason', sa.String(length=255), nullable=False),
    sa.Column('derived_from_version_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['derived_from_version_id'], ['node_versions.id'], name=op.f('fk_node_versions_derived_from_version_id_node_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_node_versions_node_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_versions')),
    sa.UniqueConstraint('node_id', 'version_no', name=op.f('uq_node_versions_node_id'))
    )
    op.create_index(op.f('ix_node_versions_node_id'), 'node_versions', ['node_id'], unique=False)
    op.create_table('review_comments',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('pr_id', sa.String(length=128), nullable=False),
    sa.Column('author', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], name=op.f('fk_review_comments_pr_id_pull_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_comments'))
    )
    op.create_index(op.f('ix_review_comments_pr_id'), 'review_comments', ['pr_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('space_id', sa.String(length=128), nullable=False),
    sa.Column('branch_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_focus', sa.Text(), nullable=True),
    sa.Column('current_objective', sa.Text(), nullable=True),
    sa.Column('resume_message', sa.Text(), nullable=True),
    sa.Column('restart_message', sa.Text(), nullable=True),
    sa.Column('owner_profile_id', sa.String(length=128), nullable=False),
    sa.Column('execution_root_node_id', sa.String(length=128), nullable=True),
    sa.Column('active_snapshot_id', sa.String(length=128), nullable=True),
    sa.Column('budget', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('pause_requested', sa.Boolean(), nullable=False),
    sa.Column('last_safe_stop_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['memory_branches.id'], name=op.f('fk_tasks_branch_id_memory_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_root_node_id'], ['nodes.id'], name=op.f('fk_tasks_execution_root_node_id_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tasks_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_tasks_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_branch_id'), 'tasks', ['branch_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_space_id'), 'tasks', ['space_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('branch_id', sa.String(length=128), nullable=False),
    sa.Column('parent_run_id', sa.String(length=128), nullable=True),
    sa.Column('run_type', sa.String(length=32), nullable=False),
    sa.Column('selected_model', sa.String(length=255), nullable=False),
    sa.Column('selected_provider', sa.String(length=255), nullable=True),
    sa.Column('route_decision_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('next_objective', sa.Text(), nullable=True),
    sa.Column('input_tokens_used', sa.Integer(), nullable=False),
    sa.Column('output_tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_used', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['memory_branches.id'], name=op.f('fk_agent_runs_branch_id_memory_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['agent_runs.id'], name=op.f('fk_agent_runs_parent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_agent_runs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_agent_runs_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_branch_id'), 'agent_runs', ['branch_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_project_id'), 'agent_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_task_id'), 'agent_runs', ['task_id'], unique=False)
    op.create_table('model_route_decisions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('agent_run_id', sa.String(length=128), nullable=True),
    sa.Column('selected_model', sa.String(length=255), nullable=False),
    sa.Column('selected_provider', sa.String(length=255), nullable=True),
    sa.Column('candidate_models', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('budget_score', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('latency_score', sa.Float(), nullable=False),
    sa.Column('route_policy_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_model_route_decisions_agent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_model_route_decisions_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_route_decisions'))
    )
    op.create_index(op.f('ix_model_route_decisions_agent_run_id'), 'model_route_decisions', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_model_route_decisions_task_id'), 'model_route_decisions', ['task_id'], unique=False)
    op.create_table('task_snapshots',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('agent_run_id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('branch_id', sa.String(length=128), nullable=False),
    sa.Column('snapshot_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resume_token', sa.String(length=255), nullable=False),
    sa.Column('context_ref', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('root_mount_ref', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('pending_writes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('pending_actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('resume_message', sa.Text(), nullable=True),
    sa.Column('safe_stop_reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('safe_to_pause', sa.Boolean(), nullable=False),
    sa.Column('blockers', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_task_snapshots_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['branch_id'], ['memory_branches.id'], name=op.f('fk_task_snapshots_branch_id_memory_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_task_snapshots_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_snapshots_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_snapshots')),
    sa.UniqueConstraint('resume_token', name=op.f('uq_task_snapshots_resume_token'))
    )
    op.create_index(op.f('ix_task_snapshots_agent_run_id'), 'task_snapshots', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_task_snapshots_branch_id'), 'task_snapshots', ['branch_id'], unique=False)
    op.create_index(op.f('ix_task_snapshots_project_id'), 'task_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_task_snapshots_task_id'), 'task_snapshots', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_snapshots_task_id'), table_name='task_snapshots')
    op.drop_index(op.f('ix_task_snapshots_project_id'), table_name='task_snapshots')
    op.drop_index(op.f('ix_task_snapshots_branch_id'), table_name='task_snapshots')
    op.drop_index(op.f('ix_task_snapshots_agent_run_id'), table_name='task_snapshots')
    op.drop_table('task_snapshots')
    op.drop_index(op.f('ix_model_route_decisions_task_id'), table_name='model_route_decisions')
    op.drop_index(op.f('ix_model_route_decisions_agent_run_id'), table_name='model_route_decisions')
    op.drop_table('model_route_decisions')
    op.drop_index(op.f('ix_agent_runs_task_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_project_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_branch_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_space_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_branch_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_review_comments_pr_id'), table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_index(op.f('ix_node_versions_node_id'), table_name='node_versions')
    op.drop_table('node_versions')
    op.drop_index(op.f('ix_edges_to_node_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_space_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_project_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_from_node_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_branch_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_source_annotations_project_id'), table_name='source_annotations')
    op.drop_index(op.f('ix_source_annotations_owner_id'), table_name='source_annotations')
    op.drop_index(op.f('ix_source_annotations_branch_id'), table_name='source_annotations')
    op.drop_table('source_annotations')
    op.drop_index(op.f('ix_pull_requests_target_branch_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_source_branch_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_project_id'), table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index(op.f('ix_nodes_space_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_project_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_parent_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_branch_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_memory_branches_space_id'), table_name='memory_branches')
    op.drop_index(op.f('ix_memory_branches_project_id'), table_name='memory_branches')
    op.drop_table('memory_branches')
    op.drop_index(op.f('ix_spaces_project_id'), table_name='spaces')
    op.drop_table('spaces')
    op.drop_index(op.f('ix_outbox_records_publish_status'), table_name='outbox_records')
    op.drop_index(op.f('ix_outbox_records_project_id'), table_name='outbox_records')
    op.drop_index(op.f('ix_outbox_records_event_type'), table_name='outbox_records')
    op.drop_index(op.f('ix_outbox_records_aggregate_type'), table_name='outbox_records')
    op.drop_index(op.f('ix_outbox_records_aggregate_id'), table_name='outbox_records')
    op.drop_table('outbox_records')
    op.drop_table('module_config_bindings')
    op.drop_index(op.f('ix_hook_contributions_module_install_id'), table_name='hook_contributions')
    op.drop_table('hook_contributions')
    op.drop_table('health_reports')
    op.drop_index(op.f('ix_event_subscriptions_module_install_id'), table_name='event_subscriptions')
    op.drop_table('event_subscriptions')
    op.drop_table('projects')
    op.drop_table('module_installs')
    # ### end Alembic commands ###